import React, { useState, useEffect } from "react";
import { downloadPDF } from "../utils/pdf";
import { FaAngleDown } from "react-icons/fa";
import { FaRocket } from "react-icons/fa";
import { FaHandRock } from "react-icons/fa";
import { FaHistory } from "react-icons/fa";
import { FaBolt } from "react-icons/fa";
import { Link } from "react-router-dom";
import { SlEnergy } from "react-icons/sl";

export default function Arrays() {
  useEffect(() => {
    if (location.pathname === "/force") {
      const scriptConfig = document.createElement("script");
      scriptConfig.innerHTML = `
      window.embeddedChatbotConfig = {
        chatbotId: "i7C9I_1eouolQfwkbX3oo",
        domain: "www.chatbase.co"
      };
    `;
      document.body.appendChild(scriptConfig);

      const scriptEmbed = document.createElement("script");
      scriptEmbed.src = "https://www.chatbase.co/embed.min.js";
      scriptEmbed.setAttribute("chatbotId", "i7C9I_1eouolQfwkbX3oo");
      scriptEmbed.setAttribute("domain", "www.chatbase.co");
      scriptEmbed.defer = true;
      document.body.appendChild(scriptEmbed);

      return () => {
        document.body.removeChild(scriptConfig);
        document.body.removeChild(scriptEmbed);
      };
    }
  }, [location.pathname]);

  useEffect(() => {
    const fadeInSections = document.querySelectorAll(".fade-in-section");

    const options = {
      threshold: 0.1,
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("is-visible");
        } else {
          entry.target.classList.remove("is-visible");
        }
      });
    }, options);

    fadeInSections.forEach((section) => {
      observer.observe(section);
    });

    return () => {
      fadeInSections.forEach((section) => {
        observer.unobserve(section);
      });
    };
  }, []);

  const questionsAndAnswers = [
    {
      question: "Why does your body lurch forward when a car suddenly stops?",
      answer: "Inertia, as described by Newton’s First Law of Motion.",
    },
    {
      question:
        "How can a tiny magnet lift a metal paperclip, defying gravity?",
      answer:
        "Magnetic force is stronger than gravitational force for small objects.",
    },
    {
      question:
        "Why do astronauts float in space even though gravity exists everywhere in the universe?",
      answer: "They are in free fall, experiencing microgravity.",
    },
    {
      question:
        "How can a small child on a seesaw lift an adult if they sit far enough from the pivot?",
      answer: "Lever principle; torque depends on distance from the pivot.",
    },
    {
      question:
        "What makes a roller coaster stay on the track during a loop-the-loop?",
      answer: "Centripetal force and inertia.",
    },
    {
      question:
        "How does a rocket generate enough force to escape Earth's gravity and reach space?",
      answer: "Thrust generated by expelling gas at high speed.",
    },
    {
      question:
        "Why does a basketball bounce higher on a hard surface compared to a soft one?",
      answer:
        "Hard surfaces absorb less energy, allowing more to be transferred back to the ball.",
    },
    {
      question: "What causes the ocean tides to rise and fall twice a day?",
      answer: "Gravitational pull of the moon and the sun.",
    },
    {
      question:
        "How can wind push a sailboat forward if the wind is blowing from the side?",
      answer: "Aerodynamic lift and the shape of the sail.",
    },
    {
      question: "Why do ice skaters spin faster when they pull their arms in?",
      answer: "Conservation of angular momentum.",
    },
    {
      question:
        "How does a bicycle stay upright when you're riding it, but falls over when it's stationary?",
      answer: "Gyroscopic effect and rider balance.",
    },
    {
      question:
        "What force keeps satellites orbiting the Earth instead of flying off into space or crashing down?",
      answer: "Gravitational force acting as a centripetal force.",
    },
  ];

  const [showAnswer, setShowAnswer] = useState(
    Array(questionsAndAnswers.length).fill(false)
  );

  const toggleAnswer = (index) => {
    setShowAnswer((prev) => {
      const newShowAnswer = [...prev];
      newShowAnswer[index] = !newShowAnswer[index];
      return newShowAnswer;
    });
  };
  const unlockNextLevel = () => {
    window.location.reload();
    window.location.href = "/forcequiz";
  };

  return (
    <div className="flex flex-col items-center justify-center bg-gradient-to-br from-green-200 to-white-500 min-h-screen">
      <style>{`
        .fade-in-section {
          opacity: 0;
          transform: translateY(20px);
          transition: opacity 0.6s ease-out, transform 0.6s ease-out;
        }

        .fade-in-section.is-visible {
          opacity: 1;
          transform: translateY(0);
        }
      `}</style>
      <div className="max-w-screen-lg mx-auto px-4" id="pdfContent">
        <h1 className="text-3xl font-bold mb-8 text-teal-800 fade-in-section">
          <FaRocket className="ml-2 inline-block text-green-500" size={32} />
          Let's talk about FORCE:From Tennis to Rocket!
        </h1>
        <p className="fade-in-section">
          <p className="font-semibold text-teal-500">
            Ever noticed how hitting a tennis ball sends it flying? That's force
            in action!
          </p>
          <br />
          When you smack that ball with your racket, you're applying force. It's
          what makes the ball zip across the court. The harder you hit it, the
          faster it goes. Simple, right?
        </p>
        <br />
        <div className="fade-in-section flex items-center justify-center">
          <img
            src="https://cdn.dribbble.com/userupload/13158937/file/original-0f688a333d932fe7d98d172c6727902c.gif"
            alt="Force in action"
            className="max-w-md w-full rounded-lg shadow-lg"
            style={{ maxWidth: "40%", height: "auto" }}
          />
        </div>
        <br />
        <p className="fade-in-section">
          Historically, the study of forces dates back to ancient civilizations,
          where early thinkers like Aristotle pondered over why objects move the
          way they do. However, it was not until the Renaissance that
          significant advancements were made in understanding forces.
        </p>
        <h2 className="text-2xl font-bold mb-4 text-teal-700 fade-in-section">
          So what exactly is FORCE?
          <FaHandRock className="ml-1 inline-block text-teal-500" size={32} />
        </h2>
        <p className="fade-in-section">
          Force is characterized by both its strength (how strong the push or
          pull is) and its direction (where the force is applied).
          <span className="font-bold text-teal-500">
            In physics, force is measured in Newtons (N), named after Sir Isaac
            Newton, who developed the laws of motion that describe how forces
            interact with objects to cause changes in their motion.
          </span>
          <br />
          <br />
          Understanding force helps explain everything from why things fall to
          the ground, to how engines and machines work, and even how planets
          orbit the sun. It's a fundamental concept that underpins much of our
          understanding of the physical world.
        </p>
        <br />
        <h2 className="text-2xl font-bold mb-4 text-teal-700 fade-in-section">
          <FaHistory className="mr-2 inline-block text-green-500" size={32} />A
          bit of history
        </h2>
        <p className="fade-in-section">
          Back in ancient times, folks like the Greeks and Egyptians were
          already onto force. They used it to move heavy stuff and build amazing
          structures. Aristotle, a big thinker from way back, had his ideas
          about how things move naturally or when you give them a shove.
        </p>
        <br />
        <span className="font-bold text-green-600">
          Fast forward to Isaac Newton in the 17th century. This guy rocked the
          science world with his laws of motion. Ever heard of "what goes up
          must come down"? That's Newton's doing. He figured out how force makes
          things speed up, slow down, or change direction.
        </span>
        <img
          src="https://media.istockphoto.com/id/1372176599/vector/science-and-physical-experience-concept.jpg?s=612x612&w=0&k=20&c=bhjKmHZwhX61zPTAno0D0d_CMwkYTM338TSn2A9qMwI="
          alt="Image 6"
          className="w-full h-auto border border-gray-300"
        />
        <br /> <br />
        Jump to more recent times—imagine the Industrial Revolution. People were
        all about machines and steam power. They figured out how to harness
        force to build trains, ships, and all kinds of cool stuff. Then, bam!
        Rockets came along, and suddenly we're sending people to space using
        force in crazy ways.
        <h2 className="text-2xl font-bold mb-4 text-teal-700 fade-in-section">
          Exploring different types of FORCEs
        </h2>
        <div className="max-w-4xl w-full">
          <ul className="divide-y divide-gray-300">
            <li className="py-4 flex items-center">
              <div className="w-1/5">
                <img
                  src="https://science.nasa.gov/wp-content/uploads/2023/09/Gravitational_Force.png?w=4096&format=png"
                  alt="Image 1"
                  className="w-full h-auto border border-gray-300"
                />
              </div>
              <div className="ml-4">
                <h2 className="text-xl font-semibold text-green-500 fade-in-section">
                  Gravitational Force
                </h2>
                <p className="mt-2 text-blue fade-in-section">
                  Ever wondered why things fall down? That's gravity at work!
                  It's what keeps us grounded on Earth and makes planets orbit
                  the sun.
                </p>
              </div>
            </li>

            <li className="py-4 flex items-center">
              <div className="w-1/5">
                <img
                  src="https://study.com/cimages/multimages/16/electrostatic_force_directions.png"
                  alt="Image 2"
                  className="w-full h-auto border border-gray-300"
                />
              </div>
              <div className="ml-4">
                <h2 className="text-xl font-semibold text-green-500 fade-in-section">
                  Electromagnetic Force
                </h2>
                <p className="mt-2 text-blue fade-in-section">
                  This one's all about electricity and magnetism. It's why
                  magnets stick together or repel each other and how electricity
                  flows through wires to power your gadgets.
                </p>
              </div>
            </li>

            <li className="py-4 flex items-center">
              <div className="w-1/5">
                <img
                  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRp_K4csiep3TaD-TYDppB2qIoD5PohwKRByw&s"
                  alt="Image 3"
                  className="w-full h-auto border border-gray-300"
                />
              </div>
              <div className="ml-4">
                <h2 className="text-xl font-semibold text-green-500 fade-in-section">
                  Normal Force
                </h2>
                <p className="mt-2 text-blue fade-in-section">
                  When you sit on a chair or stand on the ground, the surface
                  pushes back against you with a force called normal force. It's
                  what keeps you from falling through the floor!
                </p>
              </div>
            </li>

            <li className="py-4 flex items-center">
              <div className="w-1/5">
                <img
                  src="https://media.geeksforgeeks.org/wp-content/uploads/20221031174641/WhatisFrictionalForce.jpg"
                  alt="Image 4"
                  className="w-full h-auto border border-gray-300"
                />
              </div>
              <div className="ml-4">
                <h2 className="text-xl font-semibold text-green-500 fade-in-section">
                  Frictional Force
                </h2>
                <p className="mt-2 text-blue fade-in-section">
                  Ever tried to slide a heavy box across the floor? Friction is
                  the force that resists the motion between two surfaces in
                  contact. It's why your shoes grip the ground when you walk.
                </p>
              </div>
            </li>

            <li className="py-4 flex items-center">
              <div className="w-1/5">
                <img
                  src="https://www.sciencefacts.net/wp-content/uploads/2020/12/Applied-Force.jpg"
                  alt="Image 5"
                  className="w-full h-auto border border-gray-300"
                />
              </div>
              <div className="ml-4">
                <h2 className="text-xl font-semibold text-green-500 fade-in-section">
                  Applied Force
                </h2>
                <p className="mt-2 text-blue fade-in-section">
                  This is the force you apply directly, like pushing a shopping
                  cart or throwing a ball. It's your action making something
                  move.
                </p>
              </div>
            </li>

            <li className="py-4 flex items-center">
              <div className="w-1/5">
                <img
                  src="https://cloudfront.jove.com/files/media/science-education/science-education-thumbs/14698.jpg"
                  alt="Image 6"
                  className="w-full h-auto border border-gray-300"
                />
              </div>
              <div className="ml-4">
                <h2 className="text-xl font-semibold text-green-500 fade-in-section">
                  Tension Force
                </h2>
                <p className="mt-2 text-blue fade-in-section">
                  Ever pulled on a rope? Tension is the force transmitted
                  through a string, rope, cable, or any flexible connector when
                  it's pulled tight by forces acting from opposite ends.
                </p>
              </div>
            </li>
          </ul>
        </div>
        <h2 className="text-2xl font-bold mb-4 text-teal-700 fade-in-section">
          The Birth of 𝐹 = 𝑚𝑎: Newton's Eureka Moment!
        </h2>
        <p className="fade-in-action">
          One day, Newton was thinking hard about how objects move. He realized
          that if you want something to speed up or slow down (that's
          acceleration), you gotta give it a push or a pull (that's force!). But
          here’s the cool part: the harder you push (force), the faster things
          speed up (acceleration), right?
        </p>
        <br />
        <p className="font-bold text-teal-500">
          The Genius Formula Revealed: 𝐹 = 𝑚𝑎
        </p>
        <br />
        <p className="fade-in-action">
          So, Newton figured out this awesome formula: F=ma. It says that Force
          (F) equals Mass (m) times Acceleration (a).
          <br /> <span className="font-bold text-green-500">Translation?</span>
          &rarr;If you want to make something move faster (accelerate it), you
          need to apply more force—unless it's super heavy (then you need even
          more force!).
        </p>
        <br />
        <img
          src="https://i0.wp.com/probingphysics.com/wp-content/uploads/2023/09/Landscape-Blog-Banner-1-min.jpg?fit=2240%2C1260&ssl=1"
          alt="Image 6"
          className="w-full h-auto border border-gray-300"
        />
        <h2 className="text-2xl font-bold mb-4 text-teal-700 fade-in-section">
          Why it's a big deal
        </h2>
        <p className="fade-in-action">
          <span className="font-bold text-teal-500">
            Newton's formula became the superhero of physics!
          </span>{" "}
          <br />
          <br />
          It's like the ultimate cheat code for understanding how stuff moves,
          whether it's a rocket zooming into space or a skateboarder doing
          tricks. Engineers use it to build cars, scientists use it to explore
          planets, and it's basically the secret sauce behind everything from
          roller coasters to space shuttles.
        </p>
        <br />
        <h2 className="text-2xl font-bold mb-4 text-teal-700 fade-in-section">
          Derivationof 𝐹 = 𝑚𝑎: get ready!
        </h2>
        <div className="fade-in-section mb-6">
          <h2 className="text-2xl font-semibold text-green-500 mb-2">
            Step 1: Understanding Motion and Acceleration
          </h2>
          <p className="text-blue">
            First, let's understand acceleration. Imagine you're riding a
            skateboard. If you push yourself harder, you speed up faster. That
            change in speed is called acceleration.
          </p>
          <p className="text-blue mt-2">
            Mathematically, acceleration (<span className="italic">a</span>) is
            the change in velocity (&Delta;<span className="italic">v</span>)
            over time (&Delta;<span className="italic">t</span>):
          </p>
          <p className="text-blue text-center mt-4">
            <span className="italic">a</span> = &Delta;
            <span className="italic">v</span> / &Delta;
            <span className="italic">t</span>
          </p>
        </div>
        <div className="fade-in-section mb-6">
          <h2 className="text-2xl font-semibold text-green-500 mb-2">
            Step 2: Newton's First Law (Inertia)
          </h2>
          <p className="text-blue">
            Newton's First Law states that an object at rest stays at rest, and
            an object in motion stays in motion unless acted upon by an external
            force. This means if no force is applied, there is no change in
            motion (acceleration is zero).
          </p>
        </div>
        <div className="fade-in-section mb-6">
          <h2 className="text-2xl font-semibold text-green-500 mb-2">
            Step 3: Newton's Second Law (The Big Idea)
          </h2>
          <p className="text-blue">
            Newton’s Second Law tells us how force, mass, and acceleration are
            related. It states that the force applied to an object is
            proportional to the acceleration it experiences.
          </p>
          <p className="text-blue mt-2">
            Imagine you have two skateboards: one with a heavy person (more
            mass) and one with a light person (less mass). If you push both with
            the same force, the lighter person (less mass) accelerates more.
            This shows the relationship between force, mass, and acceleration.
          </p>
        </div>
        <div className="fade-in-section mb-6">
          <h2 className="text-2xl font-semibold text-green-500 mb-2">
            Step 4: Putting it All Together
          </h2>
          <p className="text-blue">
            Newton realized that the force applied to an object (
            <span className="italic">F</span>) is equal to the mass of the
            object (<span className="italic">m</span>) multiplied by its
            acceleration (<span className="italic">a</span>). This relationship
            is captured by the formula:
          </p>
          <p className="text-blue text-center mt-4">
            <span className="italic">F</span> ={" "}
            <span className="italic">m</span>
            <span className="italic">a</span>
          </p>
        </div>
        <div className="fade-in-section mb-6">
          <h2 className="text-2xl font-semibold text-green-500 mb-2">
            Step 5: From Concept to Formula
          </h2>
          <p className="text-blue">
            By combining these ideas, Newton arrived at the formula:
          </p>
          <p className="text-blue text-center mt-4">
            <span className="italic">F</span> ={" "}
            <span className="italic">m</span>
            <span className="italic">a</span>
          </p>
          <p className="text-blue mt-2">
            This formula tells us that if you know the mass of an object and how
            much you want it to accelerate, you can calculate the force needed.
          </p>
          <div className=" flex justify-center items-center">
            <img
              src="https://www.cwru.edu/artsci/phys/courses/demos/giff/fma.gif"
              alt="Image 6"
              className="w-700 h-auto border border-gray-300"
            />
          </div>
        </div>
        <div className="fade-in-section mb-6 bg-gray-400 p-4 rounded-lg">
          <h2 className="text-2xl font-semibold text-white mb-2 ">
            Practical Example
          </h2>
          <p className="text-white">
            Let's say you're throwing a basketball towards the basket:
          </p>
          <ul className="text-white list-disc list-inside mt-2">
            <li>The basketball weighs 0.6 kg.</li>
            <li>You want to accelerate the basketball at 10 m/s².</li>
          </ul>
          <p className="text-white mt-2">
            Using <span className="italic">F</span> ={" "}
            <span className="italic">m</span>
            <span className="italic">a</span>:
          </p>
          <p className="text-white text-center mt-4">
            <span className="italic">F</span> = 0.6 kg × 10 m/s² = 6 N
          </p>
          <p className="text-white mt-2">
            So, you'd need to apply 6 Newtons of force to throw the basketball.
          </p>
        </div>
        <img
          src="https://phys207-project.physics.wisc.edu/ann-seliger/wp-content/uploads/sites/4/2020/10/ezgif.com-gif-maker.gif"
          alt="Image 6"
          className="w-700 h-auto border border-gray-300"
        />
        <br />
        <h2 className="text-2xl font-bold mb-4 text-teal-700 fade-in-section">
          <FaBolt className="ml-2 inline-block text-teal-500" size={32} />
          Fun fact check!
        </h2>
        <div className="fade-in-section mb-6">
          <span className="font-bold text-teal-500">
            Ever heard of Archimedes saying he could move the Earth with a
            lever?{" "}
          </span>
          That's the power of leverage and force in action, ancient style. And
          today, force isn't just about moving stuff on Earth. It's what propels
          rockets, keeps planes in the air, and makes your car go vroom!
          <br />
          <br />
          <span className=" text-green-500">
            So, whether you're slamming a tennis ball or dreaming of Mars
            missions, understanding force is like learning the secret sauce
            behind how things move and work in our universe. Cool, huh?
          </span>
        </div>
        <br />
        <h2 className="text-2xl font-bold mb-4 text-teal-700 fade-in-section">
          Now try to think about these questions...
        </h2>
        <ul className="fade-in-section">
          {questionsAndAnswers.map((qa, index) => (
            <li key={index} className="mb-4">
              <div className="flex items-center justify-between">
                <span>{qa.question}</span>
                <button
                  onClick={() => toggleAnswer(index)}
                  className="ml-4 text-black hover:text-white"
                >
                  <FaAngleDown />
                </button>
              </div>
              {showAnswer[index] && (
                <div className="mt-2 bg-gray-400 p-2 rounded-lg">
                  {qa.answer}
                </div>
              )}
            </li>
          ))}
        </ul>
      </div>

      

      <div className="mt-4 flex space-x-4">
        <button
          className="bg-teal-800 text-white px-4 py-2 rounded-md"
          onClick={downloadPDF}
        >
          Download PDF
        </button>
        <button
          className="bg-teal-500 text-white px-4 py-2 rounded-md"
          onClick={unlockNextLevel}
        >
          Take a quiz
        </button>
        <Link
          to="/energy"
          className="bg-teal-300 text-black px-5 py-2 rounded-md flex items-center"
        >
          <SlEnergy className="mr-2 text-yellow-500 scale:200" />
          Check out ENERGY
        </Link>
      </div>
    </div>
  );
}
